---
name: ci

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:
  schedule:
  - cron: '35 4 23 * *'  # monthly on 23rd morning

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image for my etherpad-lite
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
