---
name: dockerhub

on:
  schedule:
  - cron: '7 13 * * 4'  # weekly on thursday morning
  workflow_dispatch:

jobs:
  pull-released-dockerimages:
    runs-on: ubuntu-latest
    steps:
    - name: Avoid stale tags by pulling
      run: |
        ALL_IMAGES="$(curl -s https://hub.docker.com/v2/repositories/cmur2/my-etherpad-lite/tags?page_size=1000 | jq -r '.results[].name | "cmur2/my-etherpad-lite:" + .' | grep -e 'cmur2/my-etherpad-lite:v')"
        for image in $ALL_IMAGES; do
          echo "Pulling $image to avoid staleness..."
          docker pull "$image"
        done
